from praktikum.ingredient_types import INGREDIENT_TYPE_SAUCE, INGREDIENT_TYPE_FILLING


class Data:
    BUN_NAME = 'black bun'
    BUN_PRICE = 100
    INGREDIENT_SAUCE_NAME = 'hot sauce'
    INGREDIENT_SAUCE_PRICE = 100
    INGREDIENT_SAUCE_TYPE = INGREDIENT_TYPE_SAUCE
    INGREDIENT_FILLING_NAME = 'cutlet'
    INGREDIENT_FILLING_PRICE = 100
    INGREDIENT_FILLING_TYPE = INGREDIENT_TYPE_FILLING
